# Generated by Django 3.1.7 on 2021-02-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, choices=[('QA', 'QA'), ('DEV', 'Developer'), ('MAN', 'Manager'), ('DIR', 'Director'), ('SRE', 'SRE'), ('DEVOPS', 'DevOps'), ('DESIGN', 'Designer'), ('PO', 'Projects owner')], max_length=50, null=True),
        ),
    ]
