name: ReqLock Backend
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-v2-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-v2-

      - name: Install Dependencies
        working-directory: ./backend
        env:
          PIPENV_NOSPIN: "true"
          WORKON_HOME: ~/.local/share/virtualenvs
          PIPENV_CACHE_DIR: ~/.local/share/pipcache
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: pipenv install --dev

      - name: Run pytest
        working-directory: ./backend
        env:
          PIPENV_NOSPIN: "true"
          WORKON_HOME: ~/.local/share/virtualenvs
          PYTHONPATH: "."
        run: pipenv run pytest
